"""Copy failed skeletons and their source RGB videos for inspection.

The input is one or more ``*_failed.txt`` files generated by the quality
checker.  Videos are copied from ``data/extracted`` when available, otherwise
the matching member is read directly from ``data/raw_archives/*.zip``.
"""
from __future__ import annotations

import argparse
import re
import shutil
import zipfile
from pathlib import Path


def video_name_from_skeleton(path: Path) -> str:
    name = path.name
    if not name.lower().endswith(".npz"):
        raise ValueError(f"not an npz file: {path}")
    return name[:-4] + ".avi"


def find_video(video_name: str, setup: str, extracted: Path, archives: Path):
    direct = list(extracted.glob(f"{setup}/**/{video_name}"))
    if direct:
        return ("file", direct[0])
    archive = archives / f"nturgbd_rgb_{setup}.zip"
    if not archive.exists():
        return None
    with zipfile.ZipFile(archive) as zf:
        candidates = [m for m in zf.namelist() if Path(m).name.lower() == video_name.lower()]
        if candidates:
            return ("zip", (archive, candidates[0]))
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--failed", nargs="+", default=["data/quality_reports/skeleton_quality_failed.txt"],
                        help="failed-list text files")
    parser.add_argument("--skeleton-root", default="data/skeletons_rtmw")
    parser.add_argument("--extracted", default="data/extracted")
    parser.add_argument("--archives", default="data/raw_archives")
    parser.add_argument("--output", default="data/failed_samples")
    args = parser.parse_args()

    out = Path(args.output)
    out_skel, out_video = out / "skeletons", out / "videos"
    out_skel.mkdir(parents=True, exist_ok=True)
    out_video.mkdir(parents=True, exist_ok=True)
    rows = ["sample_id,skeleton,video,status"]
    seen = set()
    for failed_file in args.failed:
        for raw in Path(failed_file).read_text(encoding="utf-8").splitlines():
            raw = raw.strip()
            if not raw or raw in seen:
                continue
            seen.add(raw)
            skel = Path(raw)
            if not skel.exists():
                # Permit report paths copied from another machine.
                matches = list(Path(args.skeleton_root).glob(f"**/{skel.name}"))
                skel = matches[0] if matches else skel
            sample_id = skel.stem.replace("_rgb", "")
            setup_match = re.search(r"S(\d{3})", sample_id, re.I)
            setup = f"s{setup_match.group(1)}" if setup_match else "s001"
            dst_skel = out_skel / setup / skel.name
            status = "skeleton_only"
            if skel.exists():
                dst_skel.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(skel, dst_skel)
            video_name = video_name_from_skeleton(skel)
            found = find_video(video_name, setup, Path(args.extracted), Path(args.archives))
            dst_video = out_video / setup / video_name
            if found and found[0] == "file":
                dst_video.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(found[1], dst_video)
                status = "copied"
            elif found and found[0] == "zip":
                dst_video.parent.mkdir(parents=True, exist_ok=True)
                with zipfile.ZipFile(found[1][0]) as zf, zf.open(found[1][1]) as src, dst_video.open("wb") as dst:
                    shutil.copyfileobj(src, dst)
                status = "copied_from_zip"
            rows.append(f"{sample_id},{dst_skel},{dst_video if status != 'skeleton_only' else ''},{status}")
    (out / "index.csv").write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"Saved {len(rows)-1} failed sample(s) to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
